---
title: 'Demo 1: T-cell ATAC-seq'
author: "Andrew"
date: "8/7/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dbplyr)
library(data.table)
library(rmarkdown)
library(knitr)
library(kableExtra)
library(rprojroot)
library(RSQLite)
library(ROMOPOmics)
knitr::opts_chunk$set(echo = TRUE)

dirs          <- list()
dirs$base     <- file.path(find_root(criterion = criteria$is_r_package))
dirs$figs     <- file.path(dirs$base,"man/figures")
dirs$demo     <- file.path(dirs$base,"demo")
dirs$data     <- file.path(dirs$demo,"data")
dirs$masks    <- file.path(dirs$demo,"masks")
```


```{r loadData}
#Data model.
dm_file   <- system.file("extdata","OMOP_CDM_v6_0_custom.csv",package="ROMOPOmics",mustWork = TRUE)
dm        <- loadDataModel(master_table_file = dm_file)

#Convert input file.
in_file   <- file.path(dirs$data,"GSE60682_standard.tsv")

#Mask.
msk_file  <- file.path(dirs$masks,"GSE60682_standard_reformat_mask.tsv")
msks      <- loadModelMasks(msk_file)

omop_inputs <- readInputFile(input_file=in_file,data_model=dm,mask_table=msks,transpose_input_table = TRUE)
db_inputs   <- combineInputTables(input_table_list = omop_inputs)
omop_db     <- buildSQLDBR(omop_tables = db_inputs,sql_db_file = file.path(dirs$base,"GSE60682_sqlDB.sqlite"))
dbListTables(omop_db)
```